# Generated by Django 3.1.3 on 2020-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
