# Generated by Django 3.1.3 on 2020-11-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0006_auto_20201109_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
