# Generated by Django 3.1.3 on 2020-11-10 10:56

from django.db import migrations, models
import truck_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0007_auto_20201109_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=100, validators=[truck_app.validators.validator_comment_end]),
        ),
    ]
