# Generated by Django 3.1.3 on 2020-11-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0009_auto_20201112_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='likes',
        ),
    ]
