# Generated by Django 3.1.3 on 2020-11-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0010_remove_truck_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_app.truck')),
            ],
        ),
    ]
