# Generated by Django 3.1.3 on 2020-11-28 15:03

from django.db import migrations, models
import truck_auth.validators


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0014_like_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='price',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='description',
            field=models.TextField(validators=[truck_auth.validators.validator_phone_only_numeric]),
        ),
    ]
