# Generated by Django 3.1.3 on 2020-11-28 15:15

from django.db import migrations, models
import truck_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0015_auto_20201128_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='truck',
            name='price',
            field=models.CharField(max_length=10, validators=[truck_app.validators.validator_price_is_digit]),
        ),
    ]
