# Generated by Django 3.1.3 on 2020-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0016_auto_20201128_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
