# Generated by Django 3.1.4 on 2020-12-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0017_auto_20201128_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(blank=True, upload_to='public/images'),
        ),
    ]
