# Generated by Django 3.1.4 on 2020-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0018_auto_20201205_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(upload_to='public/images'),
        ),
    ]
