# Generated by Django 3.1.4 on 2020-12-08 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_app', '0019_auto_20201205_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 8, 20, 27, 13, 712491)),
        ),
    ]
